version: '3.7'
services:

  filebeat:
    build: ./docker/filebeat
    image: jmorille/nginx-filebeat
    environment:
    - ELASTICSEARCH_HOST=elasticsearch
    volumes:
    - ./logs/nginx/:/var/log/nginx/
    networks:
      - esnet

networks:
  esnet: