version: '2.2'
services:

  web:
    image: nginx:1.15.4
    volumes:
      - ./config/certs:/etc/nginx/ssl:ro
      - ./config/nginx/nginx-kibana.nginx:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/ssl-optim.nginx:/etc/nginx/nginx-ssl-optim.conf:ro
      - ./config/nginx/secu-optim.nginx:/etc/nginx/nginx-secu-optim.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
    - elasticsearch
    networks:
      - esnet

#  keycloak-proxy:
#    image: jboss/keycloak-proxy:latest
#    ports:
#      - "3001:3001"
#    volumes:
#      - "./config/keycloak-proxy/proxy.json:/opt/jboss/conf/proxy.json"
#    networks:
#      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.1
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      SERVER_BASEPATH: '/kibana'
    depends_on:
      - elasticsearch
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.1
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ./config/logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet


volumes:
  esdata1:
    driver: local

networks:
  esnet: