version: '2.2'
services:

  web:
    image: nginx:1.15.4
    volumes:
      - ./config/certs:/etc/nginx/ssl:ro
      - ./config/nginx/nginx-keycloak.nginx:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/ssl-optim.nginx:/etc/nginx/nginx-ssl-optim.conf:ro
      - ./config/nginx/secu-optim.nginx:/etc/nginx/nginx-secu-optim.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - keycloak-network

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "tameresucedesbitesenenfer"
      DB_VENDOR: "POSTGRES"
      DB_USER: "keycloak"
      DB_PASSWORD: "password"
      DB_ADDR: "keycloakDB"
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8080:8080"
    depends_on:
      - keycloakDB
    networks:
      - keycloak-network
      - keycloak-backend-network

  keycloakDB:
      image: postgres:10.5
      environment:
        POSTGRES_DB: "keycloak"
        POSTGRES_USER: "keycloak"
        POSTGRES_PASSWORD: "password"
        PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - "5432:5432"
      volumes:
        - "keycloak-db-data:/var/lib/postgresql/data/pgdata"
      networks:
        - keycloak-backend-network


volumes:
  keycloak-db-data:
    driver: local

networks:
  keycloak-network:
  keycloak-backend-network: