version: '3.6'
services:

  web:
  webapp:
    build:
      context: ./docker/httpd
    volumes:
      - ./config/certs/:/etc/ssl/certs/:ro
      - ./config/httpd/httpd-kibana.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./config/nginx/ssl-optim.nginx:/etc/nginx/nginx-ssl-optim.conf:ro
#      - ./config/nginx/secu-optim.nginx:/etc/nginx/nginx-secu-optim.conf:ro
#      - ./logs/keycloack-nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - esnet


networks:
  keycloak-net:
  esnet:
