version: '3.7'
services:

  filebeat:
    build: ./docker/filebeat
    image: jmorille/nginx-filebeat
    environment:
    - ELASTICSEARCH_HOST=elasticsearch
    volumes:
    - ./logs/nginx/:/var/log/nginx/
    - ./config/certs/ca:/etc/nginx/ssl:ro
    networks:
      - esnet

networks:
  esnet: